### ISSUE TITLE
Вопрос по команде

### ISSUE THREAD

**Issue by tigra323** [DarkCat09/python-aternos#23]
Какие значения может выдать python_aternos.AternosServer.status?

**Comment by DarkCat09** [comment]
`Server.status` - эквивалент `Server._info['class']`. Это CSS-класс, который используется на веб-сайте. Пример: сервер выключен, элементу на html-странице выставляется класс `.offline`, и полоска с надписью "Offline" становится красной. То же с классом `.online`. Список их я не помню, и я их никуда не записывал, ибо не было необходимости. Надо где-то в style.css смотреть.
***
`Server.status` is an equivalent for `Server._info['class']`. It's a CSS class which is used on the web site. E.g.: the server is shutdown, the class `.offline` is set to an element on the html page and a line with the text "Offline" becomes red. The same thing with the class `.online`. I don't remember the list of classes and I didn't write it anywhere because there wasn't any need. They can be found in the file like style.css.

**Comment by tigra323** [comment]
спасибо
