### ISSUE TITLE
503 Server Error

### ISSUE THREAD

**Issue by MedCodeHack** [DarkCat09/python-aternos#74]
![image](https://github.com/DarkCat09/python-aternos/assets/129684393/aecea119-198d-4b94-99e6-498473c2fd13)

**Comment by DarkCat09** [comment]
@MedCodeHack,

Hello. Does aternos.org website works?

**Comment by Lucianoluxx** [comment]
I get the same error. It worked until about yesterday, and I did no changes to my code since then. I checked to see Aternos, and it seems like they have no issues with their services. I also wanted to see that for myself, and the website - along with starting the server - works perfectly fine.
![aternos_down](https://github.com/DarkCat09/python-aternos/assets/83650768/b541d6c8-0957-4539-ba92-d7cfb1cede7a)

**Comment by DarkCat09** [comment]
@MedCodeHack, @Lucianoluxx,

Thank you so much for the provided information.  
Looks like Aternos uses a different API endpoint or parameters for authorization now.  
Will be fixed soon.

**Comment by MedCodeHack** [comment]
> @MedCodeHack, @Lucianoluxx,
> 
> Thank you so much for the provided information. Looks like Aternos uses a different API endpoint or parameters for authorization now. Will be fixed soon.

Thx.

**Comment by MedCodeHack** [comment]
> @MedCodeHack,
> 
> Hello. Does aternos.org website work?

yes it's works fine

**Comment by MedCodeHack** [comment]
Still got the same error!

**Comment by DarkCat09** [comment]
@MedCodeHack, @Lucianoluxx,

please, check it again, should work now.
